### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by finzzz** [antoniotejada/Trilium-FindWidget#1]
Thanks for this feature Antonio!!

When using this widget, I do notice lagging when trying to type/delete a keyword.  
Is there any plan to improve this in the future?

**Comment by antoniotejada** [comment]
Can you be more specific on when it's slow? (how many characters the search word has?, is that on code notes or on text notes?, what's the note size in bytes or characters? how slow is slow, one second or more between keys?)

I use a laptop and haven't noticed much lagginess. It should only be slow (but still much less than one second) on long notes (>100KB) and only when you start typing and there are only one or two characters in the search word. Going to the next or previous occurrence should be fast no matter the search word and note sizes. 
I think that text notes (which use CKEditor's findandreplace standard implementation, not mine) are also slower than code notes (which use my implementation).

Since it's not bothering me I didn't have plans to tackle that, but there are several options that could be implemented:
- don't start the search until there are three characters in the search word.
- don't start the search until enter is pressed
- defer the searching for a few milliseconds and abort it if more chars are pressed.
- only highlight the closest N occurrences.
The main problem is that for text notes it may require reimplementing CKEditor findandreplace module.

**Comment by finzzz** [comment]
>  It should only be slow (but still much less than one second) on long notes (>100KB) and only when you start typing and there are only one or two characters in the search word. Going to the next or previous occurrence should be fast no matter the search word and note sizes.

Yes, this is the problem, my notes is >100KB. And the lagginess appears when I start typing the keyword only. It is snappy when jumping through occurrence. I would say, having the option to `start the search only when enter is pressed` is a better idea.

**Comment by antoniotejada** [comment]
Implemented findWidgetDelayMillis in https://github.com/antoniotejada/Trilium-FindWidget/commit/bda7e6f2ba7d11fcfe6df2886bd9d2813bb3969a
- set to -1 to wait for enter
- set to >=0 to set the delay after typing a character and the search starts



Closing
